# PLS

## Model

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [17]:
hit = pd.read_csv("Hitters.csv")
df = hit.copy()
df = df.dropna()
ms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

In [18]:
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])

In [19]:
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [20]:
from sklearn.cross_decomposition import PLSRegression, PLSSVD

In [21]:
pls_model = PLSRegression().fit(X_train, y_train)

In [22]:
pls_model.coef_

array([[ 2.47335600e-01,  1.13030348e+00,  2.08295898e+00,
         1.58599864e+00,  1.20781837e+00,  1.91015780e+00,
         3.55673082e+00,  1.21724059e-02,  4.94616408e-02,
         2.58964530e-01,  9.96443520e-02,  9.25548551e-02,
         9.84366218e-02,  1.77753399e-01,  4.68377973e-02,
        -1.43965788e-01,  3.51398888e+01, -7.43195797e+01,
         2.93829559e+01]])

In [23]:
pls_model = PLSRegression(n_components=2).fit(X_train, y_train)


In [24]:
pls_model.coef_


array([[ 2.47335600e-01,  1.13030348e+00,  2.08295898e+00,
         1.58599864e+00,  1.20781837e+00,  1.91015780e+00,
         3.55673082e+00,  1.21724059e-02,  4.94616408e-02,
         2.58964530e-01,  9.96443520e-02,  9.25548551e-02,
         9.84366218e-02,  1.77753399e-01,  4.68377973e-02,
        -1.43965788e-01,  3.51398888e+01, -7.43195797e+01,
         2.93829559e+01]])

## Tahmin

In [25]:
X_train.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
183  328.0   91.0   12.0  51.0  43.0   33.0    2.0   342.0    94.0    12.0   
229  514.0  144.0    0.0  67.0  54.0   79.0    9.0  4739.0  1169.0    13.0   
286  593.0  152.0   23.0  69.0  75.0   53.0    6.0  2765.0   686.0   133.0   
102  233.0   49.0    2.0  41.0  23.0   18.0    8.0  1350.0   336.0     7.0   
153  341.0   95.0    6.0  48.0  42.0   20.0   10.0  2964.0   808.0    81.0   

     CRuns   CRBI  CWalks  PutOuts  Assists  Errors  League_N  Division_W  \
183   51.0   44.0    33.0    145.0     59.0     8.0      True       False   
229  583.0  374.0   528.0    229.0    453.0    15.0      True       False   
286  369.0  384.0   321.0    315.0     10.0     6.0     False        True   
102  166.0  122.0   106.0    102.0    132.0    10.0     False       False   
153  379.0  428.0   221.0    158.0      4.0     5.0      True        True   

     NewLeague_N  
183         True  
229         True  
286        False  
102        False  
153         True

In [26]:
pls_model.predict(X_train)[0:10]

array([344.91941493, 848.87070769, 692.93622642, 185.56577984,
       435.49196077, 987.49530026, 120.63097106, 289.9263406 ,
       663.41886918, 817.90486641])

In [27]:
y_pred = pls_model.predict(X_train)

In [28]:
np.sqrt(mean_squared_error(y_train, y_pred))

310.1167593109696

In [29]:
r2_score(y_train, y_pred)

0.5140424486535481

In [30]:
y_pred = pls_model.predict(X_test)

In [31]:
np.sqrt(mean_squared_error(y_test, y_pred))

398.09956327448526